<a href="https://colab.research.google.com/github/njy622/Colab/blob/main/DataLoader_2024_02_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Dataset
- https://wikidocs.net/194918

In [19]:
import torch
from torch.utils.data import Dataset

- numpy 기준(0, 1, 2, 3) -> tensor 배열(0, 3, 1, 2)

In [21]:
class customImageDataset(Dataset):

  def __init__ (self, x_data, y_data):
    #데이터를 Tensor로 변환
    self.x_data = torch.FloatTensor(x_data)
    #Tensor로 바뀐 데이터의 차원변환(permute)
    self.x_data = self.x_data.permute(0,3,1,2)
    #자료형 변환
    self.y_data = torch.FloatTensor(y_data)
    self.len = self.y_data.shape[0]

  def __getitem__(self, index):

    return self.x_data[index], self.y_data[index]

  def __len__(self):
    return self.len


## DataLoader
- 임의의 이미지 데이터 만들기
-https://wikidocs.net/194923

In [1]:
import numpy as np

### 이미지 배열 구조

- numpy
  - (배치사이즈, 너비, 높이, 채널사이즈)
  - (0, 1, 2, 3)

- tensor
  - (배치사이즈, 채널사이즈, 너비, 높이)
  - (0, 1, 2, 3)

In [4]:
# RGB 데이터를 20장으로 만듦
train_images = np.random.randint(256, size=(20, 32, 32, 3))
train_labels = np.random.randint(10, size=(20,1))

In [5]:
train_images.shape

(20, 32, 32, 3)

- numpy
  - (배치사이즈, 너비, 높이, 채널사이즈)
  - (0, 2, 3, 1)  tensor 기준으로 구조 변경됨

- tensor
  - (배치사이즈, 채널사이즈, 너비, 높이)
  - (0, 1, 2, 3)

In [8]:
train_images[0]

array([[[124,  83, 182],
        [  7,  49, 199],
        [183, 203, 105],
        ...,
        [147, 214, 125],
        [120, 241,  31],
        [210,   0,  68]],

       [[105, 213, 172],
        [253, 193,  75],
        [ 70, 118,  78],
        ...,
        [ 11, 230, 248],
        [234, 193, 182],
        [195, 215, 226]],

       [[ 88, 129, 151],
        [ 11,   8,  49],
        [ 59, 176, 227],
        ...,
        [  4, 130, 195],
        [155, 205, 107],
        [ 13,  54,  53]],

       ...,

       [[ 87,  33, 251],
        [132,  97, 126],
        [206, 113,  18],
        ...,
        [113, 139,  64],
        [ 87, 234, 152],
        [ 36, 226, 158]],

       [[ 76,  94, 171],
        [ 28,  64, 232],
        [ 16,  41, 198],
        ...,
        [163,  44, 143],
        [201, 135, 219],
        [174, 161, 121]],

       [[236, 156, 216],
        [  6,  85, 170],
        [178, 180, 104],
        ...,
        [229, 251,  46],
        [ 11, 243, 201],
        [ 67, 180, 112]]

In [9]:
import torch
from torch.utils.data import DataLoader

In [22]:
train_data = customImageDataset(train_images, train_labels)

In [24]:
train_loarder = DataLoader(train_data, batch_size =4, shuffle=False)

In [25]:
train_loarder

### 이터레이터 객체 확인
- https://wikidocs.net/194918

In [28]:
for images, lables in train_loarder:
  print(lables)

tensor([[1.],
        [2.],
        [3.],
        [3.]])
tensor([[5.],
        [5.],
        [9.],
        [7.]])
tensor([[4.],
        [7.],
        [1.],
        [1.]])
tensor([[5.],
        [5.],
        [9.],
        [9.]])
tensor([[2.],
        [3.],
        [8.],
        [5.]])


In [ ]:
train_iter = iter(train_loarder)
train_iter.next()